apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployapp
  labels:
      app: deployapp
spec:
    replicas: 2     #desiredstate
    strategy: 
          type: RollingUpdate
    selector: 
          matchLabels:
            app: deployapp
    template: 
        metadata: 
            labels: 
              app: deployapp   
        spec: 
          containers:
             - name: frontendapp
               image: anupdudhe/frontendrds
               ports:
                  - containerPort: 80
                    protocol: TCP
               resources:
                  requests:
                        memory: "64Mi"
                        cpu: "20m"
                  limits:     
                        memory: "128Mi"
                        cpu: "50m"
               command: ["sh", "-c"]
               args:
                  - while [ 1 ]; do
                    echo "Test";
                    sleep 0.01;
                    done

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployapp
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50