apiVersion: v1
kind:  Service
metadata:
      name: clusterip
spec:
    selector:
          app:  nginxapp
    type: ClusterIP
    ports:
      - port: 80
        name: http

         
        