apiVersion: v1
kind: Pod
metadata:
        name: nginxapp
        #  label:
        #     app: nginxapp
spec:
    containers:
        - name: nginxcont
          image: nginx:latest
          resources:
              requests:
                  cpu: "5m"
                  memory: "12Mi" 
          ports:
              - protocol: TCP
                containerPort: 80
                name: http