apiVersion: v1
kind: Pod
metadata:
        name: nginxapp1
        labels:
            app: nginxapp1
spec:
    containers:
        - name: nginxcont1
          image: nginx:latest
          resources:
              requests:
                  cpu: "5m"
                  memory: "12Mi" 
          ports:
              - protocol: TCP
                containerPort: 80
                name: http