apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  volumes:
    - name: pod1
      persistentVolumeClaim:   #you mention the pvc that will be attaching to your pod
        claimName: pv-claim    #your pvc name
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:  #this parameter provides the actual path of container where it will be mounted on your external storage.
      - mountPath: "/share/local/nginx/"  #pathway of your data storage loc
        name: pod1
      ports:
       - containerPort: 80
         protocol: TCP